### ISSUE TITLE
Import MIII gait files in gait generator

### ISSUE THREAD

**Issue by bentebloks** [project-march/gait-generation#22]
Import the MIII gait files or keypoint files in the gait generator to evaluate on them and adjust them.

**Comment by Ishadijcks** [comment]
Can you upload some MIII gait files here so I can analyze them?

**Comment by bentebloks** [comment]
[MIII gait file example.tar.gz](https://github.com/project-march/gait-generation/files/3191275/MIII.gait.file.example.tar.gz)

**Comment by Ishadijcks** [comment]
@bentebloks I can read the files but I have some trouble interpreting them, can we take a look at this together when you get back?

**Comment by Olavhaasie** [comment]
No longer relevant for now and may be discussed with @project-march/v-gait
